version: '3.8'

services:
  server:
    build: .
    container_name: digital-cv-server
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm start
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: digital-cv-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: digitalResume25
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
