"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var cors = require("cors");
// import { PrismaClient } from "@prisma/client";
var default_1 = require("../node_modules/.prisma/client/default");
var authRoute_1 = require("./Routes/authRoute");
var resumeRoute_1 = require("./Routes/resumeRoute");
var prisma = new default_1.PrismaClient();
var app = express();
app.use(express.json());
app.use(cors());
app.use("/auth", authRoute_1.default);
app.use("/resume", resumeRoute_1.default);
var PORT = process.env.PORT || 5000;
app.listen(PORT, function () { return console.log("Server running on port ".concat(PORT)); });
